### ISSUE TITLE
Pairwise distances

### ISSUE THREAD

**Issue by kalebentley** [mdscheuerell/chumIPM#12]
Hey everyone,

I was able to work with Steve VanderPleough to generate a matrix of pairwise distances among "populations" (i.e., river locations/spawning areas) of Columbia River chum salmon.  I've added the .csv file to our [data folder](https://github.com/mdscheuerell/chumIPM/tree/master/data).  

I am more than happy to discuss how these distances were calculated in more detail but to get us started here are a few highlights:

- The distances are reported in feet.
- The distances were calculated using GIS stream layers and the R package '[riverdist](https://cran.r-project.org/web/packages/riverdist/index.html)'
- The list only includes Washington populations.  The stream layer that was used does not include areas outside of WA state boundaries.  In theory, areas outside WA could be added but it sounds like it may be quite a bit of work.  Obviously, not super important at the moment since our model only includes WA populations at the moment.
- I had Steve add the mouth of the Columbia River as a location/population.  Therefore...
- This data set addresses two data needs: (1) distance to mouth (potential offset for SARs), and (2) pairwise distances for hypothetical straying matrix
-  For most locations/populations, distances were calculated from the mouth of the rivers (technically 5' upstream from the mouth, I think).
- Here are a few examples:
      -- **Grays Basin** (Grays MS, Grays CJ, Grays, Gray WF)
![image](https://user-images.githubusercontent.com/40397762/132559326-e46fe622-adb8-4fd8-afbd-776a1b7de974.png)

     -- **Cowlitz River** (NOTE: currently not a population in our model)
![image](https://user-images.githubusercontent.com/40397762/132559468-adfc6ebf-1896-4dd4-9265-e33fce94617a.png)

- However, there's at least one exception (Lewis River - see below) and some nuances to the calculations for mainstem spawning areas:
     -- **Lewis River** (NOTE: again not a current population AND the GPS point is NOT at the mouth but rather approximately where spawning would begin -- at the bottom of Eagle Island.  The variation in this location vs. all others was just a miscommunication between Steve and me).
![image](https://user-images.githubusercontent.com/40397762/132560079-d38c066c-f6a9-40dd-8f8b-c056e72c37fa.png)

     -- **Ives spawning area** (have to pick a spot somewhere on the stream layer)
![image](https://user-images.githubusercontent.com/40397762/132560345-116489d5-6986-4f2e-a856-754a673081d3.png)

     -- **St. Cloud/Multnomah/Horsetail** (the distances have to follow the stream layer and so the calculations isn't necessarily the shortest path between two sites).
![image](https://user-images.githubusercontent.com/40397762/132562474-d39381c5-fe5f-4575-9ed6-cebba19c4e9b.png)

- One location that is included on this list but we haven't talked too much about is "Peterson RSI" (RSI = remote site incubator).  Without going into too much detail here, this location is on a private landowner's property located on a tiny little stream down near the mouth of the Columbia.   The exact little stream wasn't on the GIS stream layer we had so it was pinned to a nearby location.  We can probably ignore this for now since these data aren't part of the current model.  

Overall, I don't imagine these small details are super important but wanted to make you all aware.  Regardless, I am viewing these calculations as "iteration 1" and they can obviously be updated at some point in the future.  

Kale

**Comment by ebuhle** [comment]
Thanks @kalebentley (and Steve), this looks great! 

We could incorporate distance from the mouth of the Columbia as a predictor of SAR using the **salmonIPM** model as-is; it will be interesting to see whether that makes the spatial random effects distributions better-behaved or has any substantive effect on the spawner-recruit parameters.

Building out the dispersal / straying model is obviously more of a project, but as a quick and dirty first step I could plot the dispersal kernel, i.e. the distribution of known-origin adults as a function of distance from source hatchery / project. IIRC, there are relatively high proportions of Duncan Channel fish in St. Cloud, Multnomah, Horsetail and Ives, so hopefully the uncertainty in those respective pairwise distances won't obscure any underlying relationship.

**Comment by Hillsont** [comment]
@ebuhle, I took a couple of weeks off and just now catching up on older e-mails.  Not sure if I agree that "high proportions of Duncan origin adults recovered at Ives, Horsetail, Multnomah, and St Cloud".  I only have summarized data through the 2018 return but I don't think it's changed.
![image](https://user-images.githubusercontent.com/68036398/134259178-455714a3-63d2-4f37-a585-a99993574492.png)

**Comment by ebuhle** [comment]
@Hillsont, I was thinking of the proportions from the source point of view not the destination, and in terms of fish returning to a given location regardless of their ultimate disposition -- i.e., the metric that relates directly to estimating straying. That said, it's true that "relatively high" is, well, relative. Here are the raw counts over all years by `origin` (colums) and `location` (rows). The sparseness and small numbers in general definitely raise questions about how well we will be able to identify these dispersal rates, let alone extrapolate them to unknown source populations, but we're going to find out in the coming months!

```r
                 Big Creek Hatchery Duncan Channel Duncan Hatchery Grays Hatchery Lewis Hatchery Natural spawner
Duncan Creek                     NA            123               0             NA              0             623
Grays CJ                          8             NA              NA            195             NA            3400
Grays MS                         14             NA              NA           1019             NA            6510
Grays WF                          8             NA              NA            286             NA            4092
Hamilton Channel                 NA             43              14             NA              0            2313
Hamilton Creek                   NA             21              14             NA              1            1886
Hardy Creek                      NA             42               1             NA              0            1102
Horsetail                        NA              6               0             NA              0             445
I-205                            NA             13               7             NA              2            3359
Ives                             NA             57              29             NA              3            2951
Multnomah                        NA             12               4             NA              0            1354
St Cloud                         NA              5               0             NA              0             418
```

**Comment by Hillsont** [comment]
Thanks @ebuhle, it makes a lot more sense knowing you're referencing source not destination.  I don't know if it's feasible, possible, or reasonable when building out the dispersal / straying model but I would suggest grouping all of the Grays together (we have little information on site fidelity and in some years environmental conditions (low or high flow conditions) play a big part in spawning distribution), group Ives, Hamilton Creek, Hamilton Springs, and Hardy (live tagging recoveries and radio tracking studies show a bunch of mixing / exchange of adults, especially males), and group Horsetail, Multnomah, and St Cloud (live tag recoveries show mixing / exchange of adults).  There's the additional quirk that since we installed fingers in the v-weir at Hamilton Springs (in 2016 I believe), once an adult enters the channel they can't easily leave.

**Comment by ebuhle** [comment]
Thanks for those details, @Hillsont. In thinking about a dispersal kernel / straying matrix, there isn't really a natural way to re-aggregate populations -- typically in such a model, the source and sink "units" are fixed and are identical for the local dynamics and dispersal components. It might be possible to assume the straying rates to the populations within each of the groupings you mentioned are identical, e.g. by assigning them all the centroid of their respective locations and averaging the pairwise distances. I don't know if that would really make much difference since the groupings are relatively geographically clustered anyway, and it wouldn't necessarily buy us any extra degrees of freedom assuming we parameterize the dispersal matrix with an exponential kernel or something similar.
