### ISSUE TITLE
Requesting invitation to collaborate

### ISSUE THREAD

**Issue by ebuhle** [mdscheuerell/chumIPM#2]
I mean, now that WDFW is threatening to actually _pay_ me...

**Comment by ebuhle** [comment]
Hmm, it says I've already been invited as a collaborator, but I can't find that email and I don't see it in my GH notifications.

**Comment by mdscheuerell** [comment]
@ebuhle It says you are a collaborator. Can you try to commit a small change (eg, readme)?

**Comment by ebuhle** [comment]
OK, that worked. And now this repo is showing up in my GH profile, which it wasn't before. [shrug]
